### ISSUE TITLE
It this repositories work?

### ISSUE THREAD

**Issue by RozenAstrayChen** [kimhc6028/pytorch-noreward-rl#3]
Hello ! 

I find your code is old version wihth Pytorch and I update which refer [ikostrikov/pytorch-a3c](https://github.com/ikostrikov/pytorch-a3c).

I want ask this repositories is work to doom environment 'MyWayHome'? How long I need training?

**Comment by kimhc6028** [comment]
Hello, 
I haven't have updated this repo for 2 years, nor I think this repo works. This repo was made before the author publishes his own code to reproduce his work, which I finally failed to. Go to https://github.com/pathak22/noreward-rl for author's repo. I apologize for wasting your time.

**Comment by RozenAstrayChen** [comment]
Ok ,thanks for your reply.


I will check repo
